version: '3'
tasks:
  restore:
    cmds:
      - dotnet restore
  build:
    cmds:
      - dotnet build -c Release
  run:
    cmds:
      - dotnet run --project src/Orchestrator
  test:
    cmds:
      - dotnet test
  hub-up:
    cmds:
      - docker compose -f hub/deploy/docker-compose.yml up -d
  hub-down:
    cmds:
      - docker compose -f hub/deploy/docker-compose.yml down
